### ISSUE TITLE
Can't not change page 

### ISSUE THREAD

**Issue by kyunkakata** [darenju/react-native-flip-page#1]
I get this trouble in testing when using this package for android.
Please help me to fix it.
Error:
Error while updating property 'transform' of a view managed by : RCTView
null
java.lang.String cannot cast to java.lang.Double

**Comment by kyunkakata** [comment]
Log for this error:

```
08-22 10:30:36.962 3118-3118/com.testingapp E/unknown:ViewManager: Error while updating prop transform
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
```

Edit: trimmed log to necessary part.

**Comment by darenju** [comment]
Hi,

As I said before, `react-native-flip-page` is currently not officially supported on Android for now.
You'd have to wait until I get it working on Android.

**Comment by darenju** [comment]
@kyunkakata For your information, I'm starting to work on Android support.

What seems to cause the issue is the `perspective` property. But the entire behavior is weird on Android, pages are not flipping like on iOS.

Android support is limited for now.

`react-native-flip-page@0.2.5` adds support for Android. Feel free to try it.

**Comment by kyunkakata** [comment]
Thank you, i will try. Nice work,bro.

**Comment by kyunkakata** [comment]
It works perfect on Android. Keep it going bro.
