### ISSUE TITLE
Using with react native Video View

### ISSUE THREAD

**Issue by praveenvishal** [darenju/react-native-flip-page#13]
Issue in playing video when using Flip-Page with rect native video view . Can you suggest the solution . Without Flip Page video is playing normally.

**Comment by darenju** [comment]
What is the issue? Video slip in half? Normal.

**Comment by praveenvishal** [comment]
This is especially happening with android when using video view inside Flip Page , Video is splitting into two parts and not playing as normally. its working fine with ios.

**Comment by praveenvishal** [comment]
This is especially happening with android when using video view inside Flip Page , Video is splitting into two parts and not playing as normally. its working fine with ios.

**Comment by praveenvishal** [comment]
I am using android exoplayer of react native video

**Comment by praveenvishal** [comment]
Can you please help me with it.

**Comment by darenju** [comment]
It is normal that the video is split in half: this is how the component works. Maybe you could try to put the video page component on top of the flip page component when it is shown.

**Comment by praveenvishal** [comment]
But I need to use the flip page in video why is this splitting  issue
coming in case of Android only. ios works fine.

**Comment by darenju** [comment]
What are you trying to achieve exactly?

**Comment by praveenvishal** [comment]
I want the feature of flip page for various media types. Image , Video ,
Audio . I need to keep the video view inside flip page so that user can
flip it to see next page which may be image or video or audio.
image works fine for me
video in android splits in to two part
video in ios works fine i  am also able to flip the page.

**Comment by praveenvishal** [comment]
Thanks for having me your time to understand the issue. Julien can I have
your Skype or email so that I can share you the code and you understand the
issue tomorrow.

**Comment by darenju** [comment]
No, sorry, I do not do peculiar support for usage of the package, as you would understand this is my job: I get paid by customers to develop specific products.

By what you’re wanting to achieve, I think the solution I described above could be useful. You should have a « current page » component on top of the flip page component. When the page changes, you update the current page component that is displayed on top. As soon as there is a touch on the current page component, you hide it so that the visible component is the flip page. When the touch releases, you do the reverse, showing the current page component on top of the flip page.
